application: nfrom1to10
version: lt-a
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static/

- url: /tasks/*
  script: tasks.py
  login: admin

- url: /data/.*
  script: handle_data.py

- url: .*
  script: handle_pages.py
