util    = require('util')
exec    = require('child_process').exec
child   = null

js_files   = [
    'country_data'
    'pickers'
    'quiz'
    'results_overview'
    'results_ui'
]

task 'build', 'min js, compile sass', (options) ->
    commands = ("closure --js_output_file templates/js/#{ file }-min.js --js templates/js/#{ file }.js" for file in js_files)
    commands.push "compass compile -f -s compressed"

    for command in commands
        exec command, (error, stdout, stderr) ->
            console.log "stdout: #{ stdout }"
            console.log "stderr: #{ stderr }"
            if error?
                console.log "exec error: #{ error }"

