exec    = require('child_process').exec
child   = null

js_files   = [
    'country_data'
    'pickers'
    'quiz'
    'results_overview'
    'results_ui'
]

task 'build', 'min js, compile sass', (options) ->
    doCommand("compass compile -f -s compressed")

    js_files.forEach (file) ->
        coffee_compile = "coffee -c ui_source/coffee/#{ file }.coffee"
        move_js = "mv ui_source/coffee/#{ file }.js templates/js/#{ file }.js"
        closure_js = "closure --js_output_file templates/js/#{ file }-min.js --js templates/js/#{ file }.js"
        doCommand coffee_compile, ->
            doCommand move_js, ->
                doCommand closure_js, ->
                    console.log "processed #{ file }"



doCommand = (command, callback) ->
    exec command, (error, stdout, stderr) ->
        console.log "stdout: #{ stdout }"
        console.log "stderr: #{ stderr }"
        if error?
            console.log "exec error: #{ error }"
        else
            callback?()

