util    = require('util')
exec    = require('child_process').exec
child   = null

files   = [
    'country_data'
    'pickers'
    'quiz'
    'results_overview'
    'results_ui'
]

task 'closure', 'pass js through closure-compiler', (options) ->
    for file in files
        command = "closure --js_output_file templates/js/#{ file }-min.js --js templates/js/#{ file }.js"
        console.log "executing #{ command }"
        child = exec command, (error, stdout, stderr) ->
            console.log "stdout: #{ stdout }"
            console.log "stderr: #{ stderr }"
            if error?
                console.log "exec error: #{ error }"
